version: '3.8'
services:
  backend:

    build: ./Backend
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
      - /app/node_modules

  frontend:
    build: ./Frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend/src:/app/src
volumes:
  mongodb-data:
    driver: local